<?php

return [
    'USER_NOT_FOUND' => 'The provided credentials do not match with our records',
    'USER_LOGIN_SUCCESS' => 'Welcome back, ',
    'USER_REGISTER_SUCCESS' => 'Welcome to Lead CRM, ',
    'USER_PASSWORD_CHANGE_SUCCESS' => 'Password changed successfully',
    'USER_PASSWORD_CHANGE_FAILED' => 'The current password is incorrect. Please enter your valid password to change',
    'LEAD_STATUS_CHANGE_SUCCESS' => 'Lead status changed successfully',
    'LEAD_PRIORITY_CHANGE_SUCCESS' => 'Lead priority changed successfully',
    'LEAD_IMPORT_SUCCESS' => 'Lead imports successfully',
    'LEAD_UPDATED_SUCCESS' => 'Lead updated successfully',
    'LEAD_DELETED_SUCCESS' => 'Lead deleted successfully',
    'USER_ASSIGN_CHANGE_SUCCESS' => 'User assign to this lead successfully',
    'LAED_MASS_ASSIGN_SUCCESS' => 'Leads mass assign completed successfully',
    'LAED_MASS_DELETE_SUCCESS' => 'Leads mass delete completed successfully',
    'NOTE_ADDED_SUCCESS' => 'Comment added successfully',
    'NOTE_DELETED_SUCCESS' => 'Comment deleted successfully',
    'NOTES_DELETED_SUCCESS' => 'Comments deleted successfully',
    'ACTIVITIES_DELETED_SUCCESS' => 'Activities deleted successfully',
    'REMINDER_ADDED_SUCCESS' => 'Reminder added successfully',
    'REMINDER_DELTED_SUCCESS' => 'Reminder deleted successfully',
    'ENTRY_ADDED_SUCCESS' => 'Entry added successfully',
    'ENTRY_DELETED_SUCCESS' => 'Entry deleted successfully',
    'REMINDERS_UPDATED_SUCCESS' => 'Reminders updated successfully',
    'REMINDERS_DELETED_SUCCESS' => 'Reminders deleted successfully',
    'ENTRIES_DELETED_SUCCESS' => 'Entries deleted successfully',
    'SOMETHING_HAPPENED' => 'Something went wrong. Please try again later',
    'LEAD_CREATED_SUCCESS' => 'Lead created successfully',
    'USER_CREATED_SUCCESS' => 'User created successfully',
    'USER_STATUS_UPDATED_SUCCESS' => 'User status updated successfully',
    'USER_DELETED_SUCCESS' => 'User deleted successfully',
    'SETTING_UPDATE_SUCCESS' => 'Setting updated successfully',
    'DEAL_CLOSED_SUCCESS' => 'Deal closed successfully',
    'PASSWORD_RESET_CODE_SENT_SUCCESS' => 'Your password reset code successfully sent to your email',
];
